# Generated by Django 5.2.10 on 2026-02-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_vote_choice_votes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Sport',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='sport',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='question_text',
            new_name='sport_text',
        ),
    ]
